server:
  port: 8002

#spring:
#  application:
#    name: cardService #部署2个相同的服务，名字要一样
     
eureka:
  client: #客户端注册进eureka服务列表内
    serviceUrl: 
      #defaultZone: http://localhost:7001/eureka
       defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/      
  instance:
    instance-id: microservicecloud-8002
    prefer-ip-address: true     #访问路径可以显示IP地址  
      
spring:
  cloud:
    config:
      name: application #需要从github上读取的资源名称，注意没有yml后缀名
      profile: dev   #本次访问的配置项
      label: master   
      uri: http://localhost:8888  #本微服务启动后先去找8888号服务，通过SpringCloudConfig获取GitHub的服务地址    