server:
  port: 8889

spring:
  application:
    name: cardServiceConfig
  cloud:
    config:
      server:
        git:
          uri: https://github.com/guyawei2018/myRepository.git #GitHub上面的git仓库名字   
     